source 'https://rubygems.org'
ruby '1.9.3'

gem 'activesupport'
gem 'em-hiredis'
gem 'em-http-request'
gem 'em-rspec'
gem 'oauth'
gem 'rack-test'
gem 'redis'
gem 'redis-namespace'
gem 'sinatra'
gem 'thin'
gem 'tweetstream'
gem 'uuid'
gem 'webmock'
